Repository facn6/ticktack-frontend, pull requests merged in 2019-10, with the labels that each got.

#5 Adds the navbar to the main app
  src/assets/icons/cart.svg
  src/assets/icons/handicaped.svg
  src/assets/icons/menuside.svg
  src/assets/logos/tick_tack_logo.svg
  src/modules/common/components/Navbar/index.jsx
  src/modules/common/components/Navbar/style.scss
  src/modules/common/components/Sidebar/index.jsx
  src/modules/common/components/Sidebar/style.scss
  src/modules/core/components/App/index.jsx
  src/modules/core/pages/Home/index.jsx
Labels: WIP

#12 #3 add card to the home page
  src/assets/icons/circle.png
  src/assets/icons/seen.svg
  src/assets/images/arina2.jpeg
  src/assets/images/barca-real.jpg
  src/modules/common/components/Banner/index.jsx
  src/modules/common/components/Banner/style.scss
  src/modules/common/components/BannerWithButton/index.jsx
  src/modules/common/components/BannerWithButton/style.scss
  src/modules/common/components/Button/index.jsx
  src/modules/common/components/Button/style.scss
  src/modules/common/components/EventCard/index.jsx
  src/modules/common/components/EventCard/style.scss
  src/modules/common/components/Form/index.jsx
  src/modules/common/components/Form/style.scss
  src/modules/common/components/Navbar/style.scss
  src/modules/common/components/RotatingCube/style.css
  src/modules/common/components/Slider/index.jsx
  src/modules/common/components/Slider/style.scss
  src/modules/core/components/App/styles.scss
  src/modules/core/pages/Home/index.jsx
  src/modules/core/pages/Home/style.scss
Labels: done

#45 add a slider with navigation dots
  src/assets/images/anneM.jpg
  src/assets/images/anneM1.jpg
  src/assets/images/anneM2.jpg
  src/modules/common/components/Banner/style.scss
  src/modules/common/components/Footer/style.scss
  src/modules/common/components/NavSlider/index.jsx
  src/modules/common/components/NavSlider/style.scss
  src/modules/common/components/Slider/index.jsx
  src/modules/core/pages/Home/index.jsx
  src/modules/core/pages/Ticket/index.jsx
  src/modules/core/pages/Ticket/style.scss
Labels: Please Merge
